#Service Registry

version: "2"

services:
  consulserver:
    image: "skunkworxs/consul:server"
    container_name: "consulserver"
    hostname: "consulserver"
    ports:
      - "8300:8300"
      - "8301:8301"
      - "8301:8301/udp"
      - "8302:8302"
      - "8302:8302/udp"
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    command: "agent -config-dir /etc/consul.d/server.json -bootstrap"
  registry:
    image: "rackhd/registry:latest"
    container_name: "registry"
    hostname: "registry"
    links:
        - consulclient
    expose:
      - "1900"
      - "1900/udp"
      - "8300"
      - "8301"
      - "8301/udp"
      - "8302"
      - "8302/udp"
      - "8400"
      - "8500"
      - "8500/udp"
      - "8600"
      - "8600/udp"
    command: "-address=consulclient:8500"
    depends_on:
      - consulclient
  ssdpspoofer:
    build: ./cmd/ssdpspoofer
    image: "rackhd/ssdpspoofer:latest"
    container_name: "ssdpspoofer"
    hostname: "ssdpspoofer"
    expose:
      - "1900"
      - "1900/udp"
    depends_on:
        - consulserver
  consulclient:
    image: "skunkworxs/consul:client"
    container_name: "consulclient"
    hostname: "consulclient"
    expose:
      - "8300"
      - "8301"
      - "8301/udp"
      - "8302"
      - "8302/udp"
      - "8400"
      - "8500"
      - "8500/udp"
      - "8600"
      - "8600/udp"
    depends_on:
      - consulserver


